# Generated by Django 4.2.8 on 2023-12-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0004_chat_type_alter_chat_members_alter_groupchat_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
