# Generated by Django 4.2.8 on 2023-12-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0007_message_recipient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupChat',
        ),
    ]
